const LOGIN_ACTION = 'LOGIN_ACTION';
const CURRENCY_ACTION = 'CURRENCY_ACTION';
const GET_CURRENCIES = 'GET_CURRENCIES';
const FAILED_REQUEST = 'FAILED_REQUEST';

export {
  LOGIN_ACTION,
  CURRENCY_ACTION,
  GET_CURRENCIES,
  FAILED_REQUEST,
};
