const LOGIN_ACTION = 'LOGIN_ACTION';
const GET_EXCHANGE = 'GET_EXCHANGE';
const GET_CURRENCIES = 'GET_CURRENCIES';
const FAILED_REQUEST = 'FAILED_REQUEST';
const REMOVE_EXPENSE = 'REMOVE_EXPENSE';

export {
  LOGIN_ACTION,
  GET_EXCHANGE,
  GET_CURRENCIES,
  FAILED_REQUEST,
  REMOVE_EXPENSE,
};
